### ISSUE TITLE
Simulation analysis - Part 1 (basic integration)

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/.github-private#13]
Create a bare-bone path and plumbing to run a PetriNet simulation with SimulationService 

- [ ] Incorporate SimulationService.jl into the ASKEM orchestration tech stack
- [ ] Add in APIs to invoke SimulationService (create model, run simulation)
- [ ] Add in a temporary dummy tab in model page to run and display simulation output, for now we will either use default-values or use random values to run the petrinet. 

References:
https://github.com/DARPA-ASKEM/SimulationService.jl

**Comment by mwdchang** [comment]
This has been done.

Note SimulationService.jl is superseded by the simulation-scheduler (https://github.com/DARPA-ASKEM/simulation-scheduler)
