### ISSUE TITLE
Collaborate with MIT and SKEMA teams to develop rich data profiling APIs to facilitate alignment of data to models and simulations

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/.github-private#18]

**Comment by brandomr** [comment]
**Dataset metadata extraction:**

**API accepts:**
- dataset in CSV format
- [Optional] associated publication text
- [Optional] description of dataset
- [Optional] data dictionary of arbitrary form

**API returns:**
- Proposed mapping of columns to DKG concepts [nullable]
- Inferred units per column [nullable]
- Inferred data quality or generation issues [nullable]
  - requires development of quality/generation schema
