### ISSUE TITLE
Terarium Dashboard of Staging/Production

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/.github-private#22]
Webpage or service for monitoring:
 - Errors
 - Events
 - Deployments
 - etc.

**Comment by chris-dickson** [comment]
Staging:

- [x] Events
- [x] Performance
- [x] Container Info

Production:

- [ ] Events
- [ ] Performance
- [ ] Container Info

**Comment by chris-dickson** [comment]
@YohannParis @dgauldie Production now has the dashboards.
