### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/.github-private#23]
Build a `user-service`:
- [x] own java package under `Terarium/src/pakages/user-service` 
- [x] link to keycloack user management
- [x] add it to orchestration
- [ ] provide user object to be consumed by all terarium services
- [x] build the first version of the `admin-ui` webpage
    - contain all the interface for the `user-service`
    - which will include others features later on
 - [] pass user ID and project ID to TDS

**Comment by YohannParis** [comment]
So maybe another name, I wrote this quite quickly.

**Comment by bigglesandginger** [comment]
I have given it the name of "gateway-admin-keycloak" as it (currently) allows for granting roles to users, but I hope to expand it to allow for creation of roles and permissions (resources, urls like /api/foo, and the roles that are allowed to access them)

**Comment by YohannParis** [comment]
I'm not sure if this is the same as what @dgauldie was thinking, I'm sure I'm wrong: @dgauldie?
