### ISSUE TITLE
Workflow allows users to add connections between nodes and interact with nodes

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/.github-private#39]
![Image](https://user-images.githubusercontent.com/4194153/234373528-f5e2891e-e341-4847-a3ed-c7cbb48000f1.png)

![Image](https://user-images.githubusercontent.com/4194153/234374978-109aed03-017f-4147-a5ff-a9e9d7a16bc1.png)

**Comment by pascaleproulx** [comment]
This is a very high level issue. I will close it and add the parts that have not been tackled yet in other more specific issues.
